/**
 * compare_filters.c — Run KF, EKF, and UKF on the same lane dataset.
 *
 * Usage:
 *   ./compare_filters <input.csv> [output.csv]
 *
 * Input CSV: generated by python/data/export_csv.py
 *   t,speed,yaw_rate,C0_L_true,C0_R_true,C1_true,C2_true,C3_true,meas_L,meas_R
 *
 * Output CSV (per-frame estimates from all three filters):
 *   t,
 *   C0_L_true, meas_L,
 *   kf_C0_L,  ekf_C0_L,  ukf_C0_L,
 *   kf_NIS_L, ekf_NIS_L, ukf_NIS_L,
 *   C0_R_true, meas_R,
 *   kf_C0_R,  ekf_C0_R,  ukf_C0_R
 *
 * Compile:
 *   make examples
 *
 * Or manually:
 *   gcc -O2 -Wall -I../include \
 *       ../src/matrix.c ../src/kf.c ../src/ekf.c ../src/ukf.c \
 *       compare_filters.c -o compare_filters -lm
 */

#include "../include/kf.h"
#include "../include/ekf.h"
#include "../include/ukf.h"
#include "../include/matrix.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


/* ------------------------------------------------------------------ */
/* Filter parameters — match Python tuned values                        */
/* ------------------------------------------------------------------ */

#define DT           0.04

static const SigmaProcess SP = {
    .C0 = 0.07,
    .C1 = 0.004,
    .C2 = 4e-5,
    .C3 = 8e-7,
};
#define SIGMA_CAMERA 0.1

static const double P0_DIAG[4] = {0.1, 0.01, 1e-4, 1e-6};

/* UKF tuning */
#define UKF_ALPHA   1e-3
#define UKF_BETA    2.0
#define UKF_KAPPA   0.0


/* ------------------------------------------------------------------ */
/* Input CSV row                                                        */
/* ------------------------------------------------------------------ */

typedef struct {
    double t, speed, yaw_rate;
    double C0_L_true, C0_R_true;
    double C1_true, C2_true, C3_true;
    double meas_L, meas_R;
} Frame;

static int parse_csv(const char *path, Frame **out)
{
    FILE *f = fopen(path, "r");
    if (!f) { perror(path); return -1; }

    char buf[512];
    int rows = 0;
    if (!fgets(buf, sizeof(buf), f)) { fclose(f); return -1; }
    while (fgets(buf, sizeof(buf), f)) rows++;
    rewind(f);
    if (!fgets(buf, sizeof(buf), f)) { fclose(f); return -1; }

    Frame *frames = malloc(rows * sizeof(Frame));
    if (!frames) { fclose(f); return -1; }

    int n = 0;
    while (n < rows && fgets(buf, sizeof(buf), f)) {
        Frame *fr = &frames[n];
        char mL[32], mR[32];
        int got = sscanf(buf,
            "%lf,%lf,%lf,%lf,%lf,%lf,%lf,%lf,%31[^,],%31s",
            &fr->t, &fr->speed, &fr->yaw_rate,
            &fr->C0_L_true, &fr->C0_R_true,
            &fr->C1_true, &fr->C2_true, &fr->C3_true,
            mL, mR);
        if (got < 10) continue;
        fr->meas_L = (strcmp(mL,"nan")==0||strcmp(mL,"NaN")==0) ? (double)NAN : atof(mL);
        fr->meas_R = (strcmp(mR,"nan")==0||strcmp(mR,"NaN")==0) ? (double)NAN : atof(mR);
        n++;
    }
    fclose(f);
    *out = frames;
    return n;
}


/* ------------------------------------------------------------------ */
/* Running metrics                                                      */
/* ------------------------------------------------------------------ */

typedef struct {
    double sse, sae, snis;
    int    ne, nnis;
} Metrics;

static void m_update(Metrics *m, double est, double truth, double nis)
{
    if (!isnan(est) && !isnan(truth)) {
        double e = est - truth;
        m->sse += e*e;  m->sae += fabs(e);  m->ne++;
    }
    if (!isnan(nis)) { m->snis += nis; m->nnis++; }
}

static void m_print(const Metrics *m, const char *tag)
{
    double rmse = m->ne   ? sqrt(m->sse / m->ne)   : 0;
    double mae  = m->ne   ? m->sae  / m->ne        : 0;
    double nis  = m->nnis ? m->snis / m->nnis       : 0;
    printf("  %-10s  RMSE=%7.4f m   MAE=%7.4f m   mean_NIS=%6.3f\n",
           tag, rmse, mae, nis);
}

/* Phase boundaries for per-phase breakdown */
static const double PHASE_T[] = {0, 30, 50, 70, 90, 120};

static int phase_of(double t)
{
    for (int i = 0; i < 5; i++)
        if (t < PHASE_T[i+1]) return i;
    return 4;
}


/* ================================================================== */
/* main                                                                 */
/* ================================================================== */

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input.csv> [output.csv]\n", argv[0]);
        return 1;
    }

    /* ---- Load data ---- */
    Frame *frames = NULL;
    int nframes = parse_csv(argv[1], &frames);
    if (nframes <= 0) { fprintf(stderr, "Parse error\n"); return 1; }
    printf("Loaded %d frames from %s\n\n", nframes, argv[1]);

    /* ---- Initialise six filters (left + right × 3) ---- */
    double x0_L[4] = {frames[0].C0_L_true, 0, 0, 0};
    double x0_R[4] = {frames[0].C0_R_true, 0, 0, 0};

    KFState  kf_L,  kf_R;
    EKFState ekf_L, ekf_R;
    UKFState ukf_L, ukf_R;

    kf_init (&kf_L,  DT, SP, SIGMA_CAMERA, x0_L, P0_DIAG);
    kf_init (&kf_R,  DT, SP, SIGMA_CAMERA, x0_R, P0_DIAG);
    ekf_init(&ekf_L, SP, SIGMA_CAMERA, x0_L, P0_DIAG);
    ekf_init(&ekf_R, SP, SIGMA_CAMERA, x0_R, P0_DIAG);
    ukf_init(&ukf_L, SP, SIGMA_CAMERA, x0_L, P0_DIAG,
             UKF_ALPHA, UKF_BETA, UKF_KAPPA);
    ukf_init(&ukf_R, SP, SIGMA_CAMERA, x0_R, P0_DIAG,
             UKF_ALPHA, UKF_BETA, UKF_KAPPA);

    /* ---- Output CSV ---- */
    FILE *fout = NULL;
    if (argc >= 3) {
        fout = fopen(argv[2], "w");
        if (!fout) { perror(argv[2]); return 1; }
        fprintf(fout,
            "t,"
            "C0_L_true,meas_L,kf_C0_L,ekf_C0_L,ukf_C0_L,"
            "kf_NIS_L,ekf_NIS_L,ukf_NIS_L,"
            "C0_R_true,meas_R,kf_C0_R,ekf_C0_R,ukf_C0_R,"
            "kf_NIS_R,ekf_NIS_R,ukf_NIS_R\n");
    }

    /* ---- Metrics: overall + per-phase (5 phases × 3 filters × 2 sides) ---- */
    Metrics kf_L_tot  = {0}, ekf_L_tot  = {0}, ukf_L_tot  = {0};
    Metrics kf_R_tot  = {0}, ekf_R_tot  = {0}, ukf_R_tot  = {0};

    Metrics kf_L_ph[5]  = {{0}}, ekf_L_ph[5] = {{0}}, ukf_L_ph[5] = {{0}};

    /* ---- Main loop ---- */
    for (int k = 0; k < nframes; k++) {
        const Frame *fr = &frames[k];
        double u[2] = {fr->speed, fr->yaw_rate};

        /* --- Predict --- */
        kf_predict (&kf_L);
        kf_predict (&kf_R);
        ekf_predict(&ekf_L, u, DT);
        ekf_predict(&ekf_R, u, DT);
        /* UKF predict can fail (non-PD P) — guard the update on success */
        int ukf_L_ok = (ukf_predict(&ukf_L, u, DT) == 0);
        int ukf_R_ok = (ukf_predict(&ukf_R, u, DT) == 0);

        /* --- Update --- */
        double NIS_kf_L  = (double)NAN, NIS_ekf_L = (double)NAN, NIS_ukf_L = (double)NAN;
        double NIS_kf_R  = (double)NAN, NIS_ekf_R = (double)NAN, NIS_ukf_R = (double)NAN;

        if (!isnan(fr->meas_L)) {
            double z[1] = {fr->meas_L};
            if (kf_update (&kf_L,  z) == 0) NIS_kf_L  = kf_L.NIS;
            if (ekf_update(&ekf_L, z) == 0) NIS_ekf_L = ekf_L.NIS;
            if (ukf_L_ok && ukf_update(&ukf_L, z) == 0) NIS_ukf_L = ukf_L.NIS;
        }
        if (!isnan(fr->meas_R)) {
            double z[1] = {fr->meas_R};
            if (kf_update (&kf_R,  z) == 0) NIS_kf_R  = kf_R.NIS;
            if (ekf_update(&ekf_R, z) == 0) NIS_ekf_R = ekf_R.NIS;
            if (ukf_R_ok && ukf_update(&ukf_R, z) == 0) NIS_ukf_R = ukf_R.NIS;
        }

        /* --- Accumulate metrics --- */
        int ph = phase_of(fr->t);
        m_update(&kf_L_tot,  kf_L.x[0],  fr->C0_L_true, NIS_kf_L);
        m_update(&ekf_L_tot, ekf_L.x[0], fr->C0_L_true, NIS_ekf_L);
        m_update(&ukf_L_tot, ukf_L.x[0], fr->C0_L_true, NIS_ukf_L);
        m_update(&kf_R_tot,  kf_R.x[0],  fr->C0_R_true, NIS_kf_R);
        m_update(&ekf_R_tot, ekf_R.x[0], fr->C0_R_true, NIS_ekf_R);
        m_update(&ukf_R_tot, ukf_R.x[0], fr->C0_R_true, NIS_ukf_R);

        m_update(&kf_L_ph[ph],  kf_L.x[0],  fr->C0_L_true, NIS_kf_L);
        m_update(&ekf_L_ph[ph], ekf_L.x[0], fr->C0_L_true, NIS_ekf_L);
        m_update(&ukf_L_ph[ph], ukf_L.x[0], fr->C0_L_true, NIS_ukf_L);

        /* --- Write output row --- */
        if (fout) {
            /* Helper: write NaN for missing, else the value */
#define WR(v)  (isnan(v) ? fprintf(fout, "nan,") : fprintf(fout, "%.6f,", v))
            fprintf(fout, "%.4f,", fr->t);
            fprintf(fout, "%.6f,", fr->C0_L_true); WR(fr->meas_L);
            fprintf(fout, "%.6f,%.6f,%.6f,", kf_L.x[0], ekf_L.x[0], ukf_L.x[0]);
            WR(NIS_kf_L); WR(NIS_ekf_L); WR(NIS_ukf_L);
            fprintf(fout, "%.6f,", fr->C0_R_true); WR(fr->meas_R);
            fprintf(fout, "%.6f,%.6f,%.6f,", kf_R.x[0], ekf_R.x[0], ukf_R.x[0]);
            WR(NIS_kf_R); WR(NIS_ekf_R); WR(NIS_ukf_R);
#undef WR
            fprintf(fout, "\n");
        }
    }

    /* ---- Print summary tables ---- */
    printf("==========================================================\n");
    printf("  Overall — Left Marker (C0_L)\n");
    printf("==========================================================\n");
    m_print(&kf_L_tot,  "KF");
    m_print(&ekf_L_tot, "EKF");
    m_print(&ukf_L_tot, "UKF");

    printf("\n==========================================================\n");
    printf("  Overall — Right Marker (C0_R)\n");
    printf("==========================================================\n");
    m_print(&kf_R_tot,  "KF");
    m_print(&ekf_R_tot, "EKF");
    m_print(&ukf_R_tot, "UKF");

    static const char *PHASE_NAMES[] = {
        "Ph1 A9 straight",
        "Ph2 Curve",
        "Ph3 Transition",
        "Ph4 A8 straight",
        "Ph5 S-curve"
    };
    printf("\n==========================================================\n");
    printf("  Per-phase RMSE — Left Marker (m)\n");
    printf("  %-18s  %8s  %8s  %8s\n", "Phase", "KF", "EKF", "UKF");
    printf("==========================================================\n");
    for (int ph = 0; ph < 5; ph++) {
        double r_kf  = kf_L_ph[ph].ne  ? sqrt(kf_L_ph[ph].sse  / kf_L_ph[ph].ne)  : 0;
        double r_ekf = ekf_L_ph[ph].ne ? sqrt(ekf_L_ph[ph].sse / ekf_L_ph[ph].ne) : 0;
        double r_ukf = ukf_L_ph[ph].ne ? sqrt(ukf_L_ph[ph].sse / ukf_L_ph[ph].ne) : 0;
        printf("  %-18s  %8.4f  %8.4f  %8.4f\n",
               PHASE_NAMES[ph], r_kf, r_ekf, r_ukf);
    }

    if (fout) { fclose(fout); printf("\nOutput → %s\n", argv[2]); }
    free(frames);
    return 0;
}
