/**
 * lane_estimation_kf.c — C KF applied to the highway lane dataset.
 *
 * Usage:
 *   ./lane_kf <input.csv> [output.csv]
 *
 * Input CSV format (generated by python/data/generate_lane_data.py):
 *   t,speed,yaw_rate,C0_L_true,C0_R_true,C1_true,C2_true,C3_true,meas_L,meas_R
 *   (header line required; NaN for missing measurements)
 *
 * Output CSV:
 *   t,C0_L_true,meas_L,kf_C0_L,kf_C1_L,kf_C2_L,kf_C3_L,NIS_L,
 *     C0_R_true,meas_R,kf_C0_R,kf_C1_R,kf_C2_R,kf_C3_R,NIS_R
 *
 * Compile (standalone):
 *   gcc -O2 -Wall -I../include ../src/matrix.c ../src/kf.c \
 *       lane_estimation_kf.c -o lane_kf -lm
 *
 * Or use:  make examples
 */

#include "../include/kf.h"
#include "../include/matrix.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


/* ------------------------------------------------------------------ */
/* Filter parameters — match the Python tuned values                   */
/* ------------------------------------------------------------------ */

#define DT              0.04    /* camera frame period (s) = 25 Hz */

static const SigmaProcess SP = {
    .C0 = 0.07,
    .C1 = 0.004,
    .C2 = 4e-5,
    .C3 = 8e-7,
};

#define SIGMA_CAMERA    0.1     /* m — camera C0 noise std-dev */

/* Initial covariance diagonal — loose prior */
static const double P0_DIAG[KF_N] = {0.1, 0.01, 1e-4, 1e-6};


/* ------------------------------------------------------------------ */
/* CSV parsing                                                          */
/* ------------------------------------------------------------------ */

typedef struct {
    double t;
    double speed;
    double yaw_rate;
    double C0_L_true;
    double C0_R_true;
    double C1_true;
    double C2_true;
    double C3_true;
    double meas_L;    /* NaN if missing */
    double meas_R;    /* NaN if missing */
} Frame;

/**
 * parse_csv — read all frames from a CSV file.
 * Returns number of frames read, or -1 on error.
 * Caller must free(*frames).
 */
static int parse_csv(const char *path, Frame **frames_out)
{
    FILE *f = fopen(path, "r");
    if (!f) { perror(path); return -1; }

    /* Count rows (skip header) */
    int  rows   = 0;
    char buf[512];
    if (!fgets(buf, sizeof(buf), f)) { fclose(f); return -1; }
    while (fgets(buf, sizeof(buf), f)) rows++;
    rewind(f);
    if (!fgets(buf, sizeof(buf), f)) { fclose(f); return -1; }

    Frame *frames = malloc(rows * sizeof(Frame));
    if (!frames) { fclose(f); return -1; }

    int n = 0;
    while (n < rows && fgets(buf, sizeof(buf), f)) {
        Frame *fr = &frames[n];
        char mL[32], mR[32];

        int got = sscanf(buf,
            "%lf,%lf,%lf,%lf,%lf,%lf,%lf,%lf,%31[^,],%31s",
            &fr->t, &fr->speed, &fr->yaw_rate,
            &fr->C0_L_true, &fr->C0_R_true,
            &fr->C1_true, &fr->C2_true, &fr->C3_true,
            mL, mR);

        if (got < 10) continue;

        /* "nan" or "NaN" → NaN for dropout frames */
        fr->meas_L = (strcmp(mL, "nan") == 0 || strcmp(mL, "NaN") == 0)
                     ? (double)NAN : atof(mL);
        fr->meas_R = (strcmp(mR, "nan") == 0 || strcmp(mR, "NaN") == 0)
                     ? (double)NAN : atof(mR);
        n++;
    }
    fclose(f);
    *frames_out = frames;
    return n;
}


/* ------------------------------------------------------------------ */
/* Metrics                                                             */
/* ------------------------------------------------------------------ */

typedef struct {
    double sum_sq_err;
    double sum_abs_err;
    double sum_nis;
    int    n_err;
    int    n_nis;
} RunningMetrics;

static void metrics_update(RunningMetrics *m,
                            double estimate, double truth, double NIS)
{
    if (!isnan(estimate) && !isnan(truth)) {
        double e = estimate - truth;
        m->sum_sq_err  += e * e;
        m->sum_abs_err += fabs(e);
        m->n_err++;
    }
    if (!isnan(NIS)) {
        m->sum_nis += NIS;
        m->n_nis++;
    }
}

static void metrics_print(const RunningMetrics *m, const char *name)
{
    double rmse = (m->n_err > 0) ? sqrt(m->sum_sq_err / m->n_err) : 0;
    double mae  = (m->n_err > 0) ? m->sum_abs_err / m->n_err       : 0;
    double nis  = (m->n_nis > 0) ? m->sum_nis     / m->n_nis       : 0;
    printf("  %-6s  RMSE=%7.4f m   MAE=%7.4f m   mean_NIS=%6.3f\n",
           name, rmse, mae, nis);
}


/* ================================================================== */
/* main                                                                 */
/* ================================================================== */

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr,
            "Usage: %s <input.csv> [output.csv]\n"
            "  input.csv  — generated by python/data/export_csv.py\n",
            argv[0]);
        return 1;
    }

    /* ---- Load data ---- */
    Frame *frames = NULL;
    int nframes = parse_csv(argv[1], &frames);
    if (nframes <= 0) {
        fprintf(stderr, "Failed to parse %s\n", argv[1]);
        return 1;
    }
    printf("Loaded %d frames from %s\n", nframes, argv[1]);

    /* ---- Build two filters (left and right marker) ---- */
    KFState kf_L, kf_R;

    double x0_L[KF_N] = {frames[0].C0_L_true, 0.0, 0.0, 0.0};
    double x0_R[KF_N] = {frames[0].C0_R_true, 0.0, 0.0, 0.0};

    kf_init(&kf_L, DT, SP, SIGMA_CAMERA, x0_L, P0_DIAG);
    kf_init(&kf_R, DT, SP, SIGMA_CAMERA, x0_R, P0_DIAG);

    /* ---- Open output CSV ---- */
    FILE *fout = NULL;
    if (argc >= 3) {
        fout = fopen(argv[2], "w");
        if (!fout) { perror(argv[2]); return 1; }
        fprintf(fout,
            "t,"
            "C0_L_true,meas_L,kf_C0_L,kf_C1_L,kf_C2_L,kf_C3_L,NIS_L,"
            "C0_R_true,meas_R,kf_C0_R,kf_C1_R,kf_C2_R,kf_C3_R,NIS_R\n");
    }

    /* ---- Main filter loop ---- */
    RunningMetrics mL = {0}, mR = {0};

    for (int k = 0; k < nframes; k++) {
        const Frame *fr = &frames[k];

        /* --- Predict --- */
        kf_predict(&kf_L);
        kf_predict(&kf_R);

        /* --- Update (skip dropout frames) --- */
        double NIS_L = (double)NAN;
        double NIS_R = (double)NAN;

        if (!isnan(fr->meas_L)) {
            double z[KF_M] = {fr->meas_L};
            if (kf_update(&kf_L, z) == 0)
                NIS_L = kf_L.NIS;
        }
        if (!isnan(fr->meas_R)) {
            double z[KF_M] = {fr->meas_R};
            if (kf_update(&kf_R, z) == 0)
                NIS_R = kf_R.NIS;
        }

        /* --- Accumulate metrics --- */
        metrics_update(&mL, kf_L.x[0], fr->C0_L_true, NIS_L);
        metrics_update(&mR, kf_R.x[0], fr->C0_R_true, NIS_R);

        /* --- Write output row --- */
        if (fout) {
            fprintf(fout,
                "%.4f,"
                "%.6f,%.6f,%.6f,%.6f,%.6f,%.7f,%.4f,"
                "%.6f,%.6f,%.6f,%.6f,%.6f,%.7f,%.4f\n",
                fr->t,
                fr->C0_L_true, fr->meas_L,
                kf_L.x[0], kf_L.x[1], kf_L.x[2], kf_L.x[3], NIS_L,
                fr->C0_R_true, fr->meas_R,
                kf_R.x[0], kf_R.x[1], kf_R.x[2], kf_R.x[3], NIS_R);
        }

        /* --- Optional: print every 25th frame to console (1/s at 25Hz) --- */
        if (k % 25 == 0) {
            printf("t=%6.2fs  C0_L: true=%6.3f  meas=%6.3f  kf=%6.3f  NIS=%5.2f\n",
                   fr->t,
                   fr->C0_L_true,
                   isnan(fr->meas_L) ? -9.99 : fr->meas_L,
                   kf_L.x[0],
                   isnan(NIS_L)      ? -1.0  : NIS_L);
        }
    }

    /* ---- Print summary ---- */
    printf("\n--- Summary (C KF) ---\n");
    metrics_print(&mL, "Left");
    metrics_print(&mR, "Right");

    /* ---- Cleanup ---- */
    if (fout) { fclose(fout); printf("\nOutput written to %s\n", argv[2]); }
    free(frames);
    return 0;
}
